### ISSUE TITLE
CIS-BP Database .meme location

### ISSUE THREAD

**Issue by odagayev** [flatironinstitute/inferelator-prior#8]
Hi!

I'm looking to use the inferelator package and am going through the tutorial which says to use http://cisbp.ccbr.utoronto.ca/bulk.php to download .meme files for motif data, however, I don't see any options to download the .meme data format. Can you please elaborate on how to obtain those data sets outside of the ones that are provided in the tutorial? 

Thank you for taking the time to respond!

**Comment by asistradition** [comment]
Good afternoon-

The CISBP database does not provide a MEME file, unfortunately. I've updated the tutorial with how to make a MEME file, which I'm reproducing here (add the `--indirect` flag to `pwm_to_meme` if you want all motifs instead of just direct-evidence motifs).

Let me know if anything's unclear.

Thanks

First, create a MEME file from the PWMs available at [CIS-BP](http://cisbp.ccbr.utoronto.ca/bulk.php):

As an example, select the `Saccharomyces cerevisiae` species, and select the `TF info` and `PWMs` options.
Then download and uncompress the `Saccharomyces_cerevisiae_XXX.zip` file.

```ls -l
drwxr-xr-x 2 57344  pwms_all_motifs
-rw-r--r-- 1 4536   README.txt
-rw-r--r-- 1 447070 TF_Information_all_motifs_plus.txt
-rw-r--r-- 1 205424 TF_Information_all_motifs.txt
-rw-r--r-- 1 194684 TF_Information.txt
```

These loose PWM files can be formatted into a MEME file and info file with the following command:

```
python -m inferelator_prior.pwm_to_meme --motif pwms_all_motifs/* --info TF_Information_all_motifs_plus.txt --out Scer.cisbp.meme
```

The motif information can then be summarized from the created MEME file

```
python -m inferelator_prior.motif_information --motif Scer.cisbp.meme --out Scer.cisbp.info.tsv
```

**Comment by odagayev** [comment]
Thank you so much!

**Comment by emar-143** [comment]
Hi, 

I am trying to do the same thing as odagayev - convert pwm files from CIS-BP into meme format. I am having difficulty achieving this however. I am trying to run the following code in terminal:

 `python3 -m inferelator_prior.pwm_to_meme --motif pwms_all_motifs/* --info TF_Information_all_motifs_plus.txt --out Scer.cisbp.meme`

But I keep getting the error:

`/usr/local/bin/python3: Error while finding module specification for 'inferelator_prior.pwm_to_meme' (ModuleNotFoundError: No module named 'inferelator_prior')`

Any help you could offer to solve this would be greatly appreciated. Do you know any other ways to convert these PWM.txt files to meme format? Please let me know if there is any more information you need from me to do this.

Thanks for your help!

**Comment by asistradition** [comment]
`ModuleNotFoundError: No module named 'inferelator_prior'` would suggest that you have not installed the base package with `python -m pip install inferelator_prior` or by cloning the github repo and running the `setup.py` script. Are you sure you have installed this into your package library?

**Comment by emar-143** [comment]
Ahhh yup that was it, I was trying to use inferelator instead of inferelator_prior. Thanks for your help!
